# Generated by Django 5.1.6 on 2025-02-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
