# Generated by Django 5.1.6 on 2025-02-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profileimage_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
