# Generated by Django 5.1.6 on 2025-03-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_review_person_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(blank=True, choices=[('travel', 'Travel'), ('meditation', 'Meditation'), ('running', 'Running'), ('sports', 'Sports'), ('hiking', 'Hiking'), ('gardening', 'Gardening'), ('tech', 'Technology'), ('music', 'Music'), ('photography', 'Photography'), ('cinematography', 'Cinematography'), ('baking', 'Baking'), ('cooking', 'Cooking')], max_length=100),
        ),
    ]
