# Generated by Django 5.1.6 on 2025-02-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profileimage_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='profile_image',
            new_name='image_url',
        ),
    ]
