# Generated by Django 5.1.6 on 2025-03-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_category_remove_event_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
