# Generated by Django 5.1.6 on 2025-03-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_image_delete_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
